### ISSUE TITLE
FR: Also rename files in Nuclide's Open Files Panel

### ISSUE THREAD

**Issue by stowball** [joshwcomeau/nice-index#8]
While this plugin works well on the tabs, it would be awesome if it could also work with Nuclide's Open Files (and maybe Uncommitted Changes?) panels.

Here's what mine currently look like 😞 
![image](https://user-images.githubusercontent.com/853552/29652088-2f7b0b0a-88e7-11e7-9287-7e43934f3607.png)

**Comment by joshwcomeau** [comment]
Ah that sucks D:

Truthfully I don't foresee having the time/inclination to fix this. I don't even use Atom much anymore these days (my work's codebase is sufficiently huge that Sublime just makes more sense :( )

More than happy to accept a PR that fixes this!

**Comment by stowball** [comment]
I just came up with a quick n dirty CSS solution to it:

```less
.nuclide-file-tree-open-files-list {
  .file.list-item[data-name="index.js"] {
    &::after {
      content: attr(data-path);
      direction: rtl;
      overflow: hidden;
      position: absolute;
      right: -4px;
      width: ~"calc(100% - 56px)";
    }

    .nuclide-ui-path-with-file-icon.icon-file-text {
      visibility: hidden;

      &::before {
        visibility: visible;
      }
    }
  }
}
```

which renders as 
![image](https://user-images.githubusercontent.com/853552/30362057-5b4f7912-989d-11e7-83ca-f535b3350ad3.png)
